export default function Head() {
  return (
    <>
      <title>Account</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://img.icons8.com/pastel-glyph/256/c11b3f/warning-triangle.png"
        type="image/png"
      />
    </>
  );
}
